[build]
  publish = "dist/anytura-photo/browser"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"
  NETLIFY_USE_PNPM = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 